import Head from 'next/head'
import Header from '../../components/WelcomePage/Header'
import Hero from '../../components/WelcomePage/Hero'
import Footrt from '../../components/WelcomePage/Footrt'



export default function WelcomePage() {
  return (
    <>
      <Head>
        <title>Avalanche</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
       
      </Head>
      <main className="w-full">
       <Header />
       <Hero />
       <Footrt />
      </main>
    </>
  )
}