import Head from 'next/head'
import NavBar from '../../components/shared/NavBar'
import SideBar from '../../components/shared/SideBar'
import Footrt from '../../components/WelcomePage/Footrt'

export default function  marketplace() {
  return (
    <>
      <Head>
        <title>Avalanche</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
       
      </Head>
      <main className="w-full">
       <NavBar />
       <div className='w-full min-h-screen flex  mt-[70px] bg-gray-900 '>
       <SideBar />
       </div>
       <Footrt />
      
      </main>
    </>
  )
}