import Head from 'next/head'
import { useState } from 'react'
import WelcomePage from "./public/index"



export default function Home() {
  const [isAuthenticated, setIsAuthenticated] = useState<boolean>(false);

  if(!isAuthenticated) {

    return <WelcomePage />

  }
  

  return (
    <>
      <Head>
        <title>Avalanche</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
       
      </Head>
      <main className="container">
        <h1>you logged in you made it bro!</h1>
      </main>
    </>
  )
}
